%% 1. Generating Propagated Error Formulas

% Eq. 1 
syms rho_air g h_manometer rho_h2o error_h_manometer
V_outlet_incremental = (2*rho_h2o*g*h_manometer/rho_air)^0.5;
error_V_outlet_incremental = abs(diff(V_outlet_incremental,h_manometer)...
    *error_h_manometer);

% Eq. 2
syms V_outlet_max_incremental error_V_outlet_incremental
V_outlet_bulk = 0.85*V_outlet_max_incremental;
error_V_outlet_bulk = abs(diff(V_outlet_bulk,V_outlet_max_incremental)*...
    error_V_outlet_incremental);

% Eq. 3
syms d_outlet error_d_outlet
A_outlet = pi/4*d_outlet^2;
error_A_outlet = abs(diff(A_outlet,d_outlet))*error_d_outlet;

% Eq. 4
syms V_outlet_bulk error_V_outlet_incremental A_outlet error_A_outlet
Q_outlet = V_outlet_bulk*A_outlet;
error_Q_outlet = abs(diff(Q_outlet,V_outlet_bulk)*...
    error_V_outlet_incremental) + abs(diff(Q_outlet,A_outlet)*...
    error_A_outlet);

% Eq. 5
syms V_outlet_bulk d_outlet nu error_V_outlet_incremental error_d_outlet
Re_outlet = V_outlet_bulk*d_outlet/nu;
error_Re_outlet = abs(diff(Re_outlet,V_outlet_bulk)*...
    error_V_outlet_incremental) + abs(diff(Re_outlet,d_outlet)*...
    error_d_outlet);

% Eq. 6
syms Cd A_orifice hloss_orifice_meas rho_h2o g rho_air B error_A_orifice error_hloss_orifice_meas
Q_orifice = Cd*A_orifice*((2*(hloss_orifice_meas)*rho_h2o*g)/...
    (rho_air*(1-B^4)))^0.5;
error_Q_orifice = abs(diff(Q_orifice,A_orifice)*error_A_orifice) +...
    abs(diff(Q_orifice,hloss_orifice_meas)*error_hloss_orifice_meas);

% Eq. 7
syms d_orifice error_d_orifice
A_orifice = pi/4*d_orifice^2;
error_A_orifice = abs(diff(A_orifice,d_orifice))*error_d_orifice;

% Eq. 8
syms epsilon d_outlet Re_orifice error_d_outlet error_Re_orifice
f = (1/(-2*log10((epsilon/d_outlet)/3.7-2.51/Re_orifice*(1.8*...
    log10(((epsilon/d_outlet)/3.7)^1.11+6.9/Re_orifice)))))^2;
error_f = abs(diff(f,d_outlet)*error_d_outlet) + abs(diff(f,Re_orifice)*...
    error_Re_orifice);

% Eq. 9a
syms rho_air rho_h2o g f Q_orifice A_outlet A_orifice f_minor L_orifice d_outlet error_f error_Q_orifice error_A_outlet error_A_orifice error_L_orifice error_d_outlet
hloss_orifice_calc = (rho_air/(2*g*rho_h2o))*((Q_orifice/A_orifice)^2 -...
    (Q_orifice/A_outlet)^2 + (Q_orifice/A_orifice)^2*(f*L_orifice/...
    d_orifice + f_minor))...
    - (rho_air/(2*g*rho_h2o))*((Q_orifice/A_outlet)^2 -...
    (Q_orifice/A_orifice)^2 + (Q_orifice/A_outlet)^2*(f*L_orifice/...
    d_outlet + f_minor));
error_hloss_orifice_calc = abs(diff(hloss_orifice_calc,f)*error_f)...
    + abs(diff(hloss_orifice_calc,L_orifice)*error_L_orifice)...
    + abs(diff(hloss_orifice_calc,d_outlet)*error_d_outlet)...
    + abs(diff(hloss_orifice_calc,Q_orifice)*error_Q_orifice)...
    + abs(diff(hloss_orifice_calc,A_outlet)*error_A_outlet)...
    + abs(diff(hloss_orifice_calc,A_orifice)*error_A_orifice);

% Eq. 9b
syms h13 h14 error_h_meas
hloss_orifice_meas = h13-h14;
error_hloss_orifice_meas = abs(diff(hloss_orifice_meas,h13)*...
    error_h_meas)+abs(diff(hloss_orifice_meas,h14)*error_h_meas);

% Eq. 10
syms Q_orifice d_outlet A_outlet nu error_Q_orifice error_d_outlet error_A_outlet
Re_orifice = Q_orifice*d_outlet/(A_outlet*nu);
error_Re_orifice = abs(diff(Re_orifice,Q_orifice)*error_Q_orifice) +...
    abs(diff(Re_orifice,d_outlet)*error_d_outlet)+...
    abs(diff(Re_orifice,A_outlet)*error_A_outlet);


%% 2. Solving for Propagated Error Using Section 1 Output

% Constants

nu = 1.52e-5; % for air [m^2/s]
g = 9.81; % [m/s^2]
rho_h2o = 998; % [kg/m^3]
rho_air = 1.2; % [kg/m^3]
Cd = 0.6;
B = 0.5;
epsilon = 1.5e-6; % [m]
L_orifice = 0.2286; % 9" length from plate to either inlet or outlet [m]
error_L_orifice = 0.0005; % [m]
f_minor = 0.00; % minor losses across orifice
d_orifice = 0.0254001; % [m]
error_d_orifice = 0.0005; % [m]
d_outlet = 0.0508; % [m]
error_d_outlet = 0.0005; % [m]
error_h_manometer = 0.0005; % [m H2O] 1/2 of 1 mm H2O increment

% Selecting the Design-Specific Parameters

design = 1;

if design ==1
    h_manometer = 0.00624; % Design 1 at increment = 1 mm
    V_outlet_max_incremental = 12.5284; % Design 1
    h13 = 19.00843182/100; % [m H2O] Design 1, average reading
    h14 = -6.618632727/100; % [m H2O] Design 1, average reading
    error_h_meas = 0.006308814/100; % [m H2O] avg. std error of ch. 13, 14   
elseif design ==2
    h_manometer = 0.00696; % Design 2 at increment = 1 mm 
    V_outlet_max_incremental = 12.3708; % Design 2
    h13 = 19.15865/100; % [m H2O] Design 2, average reading
    h14 = -6.791395208/100; % [m H2O] Design 2, average reading
    error_h_meas = 0.004488695/100; % [m H2O] avg. std error of ch. 13, 14
end

% Calculations

% Eq. 3
A_outlet =(pi*d_outlet^2)/4;
error_A_outlet =(pi*error_d_outlet*abs(d_outlet))/2;

% Eq. 7
A_orifice =(pi*d_orifice^2)/4;
error_A_orifice =(pi*error_d_orifice*abs(d_orifice))/2;

% Eq. 1
V_outlet_incremental = ((2*g*h_manometer*rho_h2o)/rho_air)^(1/2);
error_V_outlet_incremental = abs(error_h_manometer*g*rho_h2o)/...
    (abs(rho_air)*((2*abs(g*h_manometer*rho_h2o))/abs(rho_air))^(1/2));
 
% Eq. 2
V_outlet_bulk = (17*V_outlet_max_incremental)/20;
error_V_outlet_bulk = (17*abs(error_V_outlet_incremental))/20;

% Eq. 4
Q_outlet = A_outlet*V_outlet_bulk;
error_Q_outlet = abs(A_outlet*error_V_outlet_incremental) +...
    abs(V_outlet_bulk*error_A_outlet);

% Eq. 5
Re_outlet = (V_outlet_bulk*d_outlet)/nu;
error_Re_outlet = abs(V_outlet_bulk*error_d_outlet)/abs(nu) +...
    abs(d_outlet*error_V_outlet_incremental)/abs(nu);

% Eq. 9b
hloss_orifice_meas = h13 - h14;
error_hloss_orifice_meas = 2*abs(error_h_meas);

% Eq. 6
Q_orifice = A_orifice*Cd*(-(2*g*hloss_orifice_meas*rho_h2o)/...
    (rho_air*(B^4 - 1)))^(1/2);
error_Q_orifice = abs(Cd*error_A_orifice)*((2*abs(g*...
    hloss_orifice_meas*rho_h2o))/(abs(B^4 - 1)*abs(rho_air)))^(1/2) ...
    + abs(A_orifice*Cd*error_hloss_orifice_meas*g*rho_h2o)/...
    (abs(B^4 - 1)*abs(rho_air)*((2*abs(g*hloss_orifice_meas*rho_h2o))...
    /(abs(B^4 - 1)*abs(rho_air)))^(1/2));

% Eq. 10
Re_orifice =(Q_orifice*d_outlet)/(A_outlet*nu);
error_Re_orifice = abs(Q_orifice*error_d_outlet)/(abs(A_outlet)*...
    abs(nu)) + abs(d_outlet*error_Q_orifice)/(abs(A_outlet)*...
    abs(nu)) + abs(Q_orifice*d_outlet*error_A_outlet)/...
    (abs(A_outlet)^2*abs(nu));

% Eq. 8
f = log(10)^2/(4*log((10*epsilon)/(37*d_outlet) - (2259*...
    log(69/(10*Re_orifice) + ((10*epsilon)/(37*d_outlet))^(111/100)))...
    /(500*Re_orifice*log(10)))^2);
error_f =(log(10)^2*abs(error_d_outlet*((10*epsilon)/(37*d_outlet^2)...
    - (6777*epsilon*((10*epsilon)/(37*d_outlet))^(11/100))/...
    (5000*Re_orifice*d_outlet^2*log(10)*(69/(10*Re_orifice) + ...
    ((10*epsilon)/(37*d_outlet))^(111/100))))))/(2*abs(log((10*...
    epsilon)/(37*d_outlet) - (2259*log(69/(10*Re_orifice) + ((10*...
    epsilon)/(37*d_outlet))^(111/100)))/(500*Re_orifice*log(10))))^3*...
    abs((10*epsilon)/(37*d_outlet) - (2259*log(69/(10*Re_orifice) +...
    ((10*epsilon)/(37*d_outlet))^(111/100)))/(500*Re_orifice*...
    log(10)))) + (log(10)^2*abs(error_Re_orifice*(155871/(5000*...
    Re_orifice^3*log(10)*(69/(10*Re_orifice) + ((10*epsilon)/(37*...
    d_outlet))^(111/100))) + (2259*log(69/(10*Re_orifice) + ((10*...
    epsilon)/(37*d_outlet))^(111/100)))/(500*Re_orifice^2*log(10)))))/...
    (2*abs(log((10*epsilon)/(37*d_outlet) - (2259*log(69/(10*Re_orifice)...
    + ((10*epsilon)/(37*d_outlet))^(111/100)))/(500*Re_orifice*...
    log(10))))^3*abs((10*epsilon)/(37*d_outlet) - (2259*log(69/(10*...
    Re_orifice) + ((10*epsilon)/(37*d_outlet))^(111/100)))/(500*...
    Re_orifice*log(10))));
 
% Eq. 9a
hloss_orifice_calc = (rho_air/(2*g*rho_h2o))*((Q_orifice/A_orifice)^2 -...
    (Q_orifice/A_outlet)^2 + (Q_orifice/A_orifice)^2*(f*L_orifice/...
    d_orifice + f_minor))...
    - (rho_air/(2*g*rho_h2o))*((Q_orifice/A_outlet)^2 -...
    (Q_orifice/A_orifice)^2 + (Q_orifice/A_outlet)^2*(f*L_orifice/...
    d_outlet + f_minor));
error_hloss_orifice_calc = abs(error_A_outlet*((rho_air*((2*Q_orifice^2)...
    /A_outlet^3 + (2*Q_orifice^2*(f_minor + (L_orifice*f)/...
    d_outlet))/A_outlet^3))/(2*g*rho_h2o) - (Q_orifice^2*rho_air)/...
    (A_outlet^3*g*rho_h2o))) + abs(error_A_orifice*((rho_air*((2*...
    Q_orifice^2)/A_orifice^3 + (2*Q_orifice^2*(f_minor + ...
    (288230376151711744*L_orifice*f)/7321080377291093))/A_orifice^3))/...
    (2*g*rho_h2o) - (Q_orifice^2*rho_air)/(A_orifice^3*g*rho_h2o))) +...
    abs(error_f*((144115188075855872*L_orifice*Q_orifice^2*rho_air)/...
    (7321080377291093*A_orifice^2*g*rho_h2o) + (L_orifice*Q_orifice^2*...
    rho_air)/(2*A_outlet^2*d_outlet*g*rho_h2o))) + abs(error_Q_orifice*...
    ((rho_air*((2*Q_orifice)/A_outlet^2 - (2*Q_orifice)/A_orifice^2 +...
    (2*Q_orifice*(f_minor + (L_orifice*f)/d_outlet))/A_outlet^2))/(2*g*...
    rho_h2o) + (rho_air*((2*Q_orifice)/A_orifice^2 - (2*Q_orifice)/...
    A_outlet^2 + (2*Q_orifice*(f_minor + (288230376151711744*L_orifice*...
    f)/7321080377291093))/A_orifice^2))/(2*g*rho_h2o))) + ...
    abs(error_L_orifice*((144115188075855872*Q_orifice^2*f*rho_air)...
    /(7321080377291093*A_orifice^2*g*rho_h2o) + (Q_orifice^2*f*rho_air)...
    /(2*A_outlet^2*d_outlet*g*rho_h2o))) + (abs(L_orifice*...
    error_d_outlet*f*rho_air)*abs(Q_orifice)^2)/(2*abs(A_outlet)^2*...
    abs(d_outlet)^2*abs(g)*abs(rho_h2o));


%% 3. Results (Equations 1 to 10 are Printed in Order)

V_outlet_incremental, error_V_outlet_incremental, ...
    V_outlet_bulk, error_V_outlet_bulk, A_outlet, error_A_outlet,...
    Q_outlet, error_Q_outlet, Re_outlet, error_Re_outlet, Q_orifice,...
    error_Q_orifice, A_orifice, error_A_orifice, f, error_f,...
    hloss_orifice_calc, error_hloss_orifice_calc, hloss_orifice_meas,...
    error_hloss_orifice_meas, Re_orifice, error_Re_orifice;

f^0.5

